<?php

class RPartListItemUpdateProcessor extends modObjectUpdateProcessor
{
    public $objectType = 'RPartListItem';
    public $classKey = 'RPartListItem';
    public $languageTopics = ['rpartlist'];


    public function process()
    {
        $id = (int)$this->getProperty('id');
        $name = trim($this->getProperty('name'));

        // запись в лог
        $user_id = $this->modx->user->id;
        if ($user_id) {
            $query = $this->modx->newQuery('modUser',array('`modUser`.`id`' => $user_id));
            $query->innerJoin('modUserGroupMember','UserGroupMembers');
            $query->innerJoin('modUserGroup','UserGroup','`UserGroupMembers`.`user_group` = `UserGroup`.`id`');
            $query->select('UserGroup.name');
            $groupsArray = array();
            if ($query->prepare() && $query->stmt->execute()) {
                while($row = $query->stmt->fetch(PDO::FETCH_ASSOC)) { $groupsArray[] = $row['name']; }
            }

            $userGroups = implode(',',$groupsArray);

            $create_log = $this->modx->newObject('RPartLog');
            $create_log->set('user_id', $user_id);
            $create_log->set('user_name', $this->modx->user->fullname);
            $create_log->set('groups_id', $userGroups);
            $create_log->set('action', 'Обновлен => ' . '(' . $id . ') - ' . $name);
            $create_log->set('action_date', date("Y-m-d H:i:s"));
            $create_log->save();
        }

        return parent::process(); // TODO: Change the autogenerated stub
    }


    /**
     * We doing special check of permission
     * because of our objects is not an instances of modAccessibleObject
     *
     * @return bool|string
     */
    public function beforeSave()
    {
        if (!$this->checkPermissions()) {
            return $this->modx->lexicon('access_denied');
        }

        return true;
    }


    /**
     * @return bool
     */
    public function beforeSet()
    {
        $id = (int)$this->getProperty('id');
        $name = trim($this->getProperty('name'));
        $brand_id = trim($this->getProperty('brand_id'));
        if (empty($id)) {
            return $this->modx->lexicon('rpartlist_item_err_ns');
        }

        if (empty($name)) {
            $this->modx->error->addField('name', $this->modx->lexicon('rpartlist_item_err_name'));
        } elseif ($this->modx->getCount($this->classKey, ['name' => $name, 'brand_id' => $brand_id, 'id:!=' => $id])) {
            $this->modx->error->addField('name', $this->modx->lexicon('rpartlist_item_err_ae'));
        }

        return parent::beforeSet();
    }
}

return 'RPartListItemUpdateProcessor';
